### ISSUE TITLE
Allow `lizard` to run on non-C code as well

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#49]
Specifically, allow it to run on Fortran as well. `lizard` appears to support it already, so it might be possible out of the box, just by relaxing the regex constraints.

**Comment by LecrisUT** [comment]
@Takishima note that fortran compilers are very picky about their extension case sensitivity, i.e. `.F90` is more widely used than `.f90`.

Wouldn't it be more appropriate to just take all the files in `compile_commands.json` and run over all of them there?

**Comment by Takishima** [comment]
> @Takishima note that fortran compilers are very picky about their extension case sensitivity, i.e. `.F90` is more widely used than `.f90`.

Did not know that. It's now fixed.
 
> Wouldn't it be more appropriate to just take all the files in `compile_commands.json` and run over all of them there?

I'll think about it, though I would need to figure out a way to make sure that the `include` and `exclude` directives from pre-commit configuration file also applies to them...
