### ISSUE TITLE
Support for C++ modules

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#62]
Should add a few file extensions of `.cppm`, `.ixx`, etc.

**Comment by Takishima** [comment]
Happy to do so.

Which ones exactly would you be interested in getting by default?

**Comment by LecrisUT** [comment]
CLion supported extensions are:
`cppm|ixx|mxx|ccm|cxxm|c++m`

**Comment by Takishima** [comment]
Ok, got that. I will be adding support for them by default in a future merge request.
