### ISSUE TITLE
clang-tidy fails in preset mode

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#63]
The issue is that it still uses default:
```
Unable to locate /path/to/project/.cmake_build/compile_commands.json
```
Even though the preset will use a different build directory. For some reason `clang-format` did not create this issue.

**Comment by Takishima** [comment]
Hi,
So far I have not used the preset feature with CMake that much, which is why I never encountered this issue.

So essentially, you define the build directory within the preset file? (And I'm assuming that it is a CMake file?)

**Comment by Takishima** [comment]
The reason why clang-format is not impacted is because clang-format does not use the `compile_commands.json` file at all.

**Comment by LecrisUT** [comment]
> Hi, So far I have not used the preset feature with CMake that much, which is why I never encountered this issue.
> 
> So essentially, you define the build directory within the preset file? (And I'm assuming that it is a CMake file?)

It is a json file, but it is rather complicated to make a json parser for it. I am not sure how CLion parses it. I was thinking we could use cmake-file-api, but we need to know the build directory to use it :(

**Comment by Takishima** [comment]
Would you be able to either post the relevant parts in this discussion?
Parsing json using Python should be pretty easy if I know what to look for.

Also, does this need to be specified on the CMake command line?

**Comment by LecrisUT** [comment]
So the issue is that:
- you have multiple sources to pull and merge from: `CMakePresets.json`, `CMakeUserPresets.json`, and all the files in the `include` field inside it. Plus different supported behaviours on different versions
- the `build_dir` is run relative to `source_dir` and these can depend on macros

I will raise an issue upstream to enable outputting the parsed preset. For now how about a check that if `--preset` is passed, make sure `-B` is also defined.
